$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$RefLib = Join-Path (Split-Path -Parent $Root) "OpenSynaptic\libraries"
$OutFile = Join-Path $Root "src\osfx_library_data.generated.h"

function Escape-CString([string]$s) {
    if ($null -eq $s) { return "" }
    return ($s -replace "\\", "\\\\" -replace '"', '\\"')
}

function Get-Json([string]$path) {
    return (Get-Content -Raw -Encoding UTF8 $path | ConvertFrom-Json)
}

$symbols = Get-Json (Join-Path $RefLib "OS_Symbols.json")
$prefixes = Get-Json (Join-Path $RefLib "Prefixes.json")

$unitMap = @{}
Get-ChildItem -Path (Join-Path $RefLib "Units") -Filter "*.json" | ForEach-Object {
    $j = Get-Json $_.FullName
    $baseUnit = $j.__METADATA__.base_unit
    foreach ($p in $j.units.PSObject.Properties) {
        $k = [string]$p.Name
        $v = $p.Value
        $lk = $k.ToLowerInvariant()
        $ucum = if ($v.ucum_code) { [string]$v.ucum_code } else { $k }
        $factor = [double]$v.to_standard_factor
        $offset = [double]$v.to_standard_offset
        $canPrefix = if ($v.can_take_prefix -eq $true) { 1 } else { 0 }
        if (-not $unitMap.ContainsKey($lk)) {
            $unitMap[$lk] = [PSCustomObject]@{
                key = $k
                ucum = $ucum
                base_unit = [string]$baseUnit
                factor = $factor
                offset = $offset
                can = $canPrefix
            }
        }
    }
}

$prefixRows = @()
foreach ($p in $prefixes.decimal_prefixes.PSObject.Properties) {
    $prefixRows += [PSCustomObject]@{ key = [string]$p.Name; factor = [double]$p.Value.f }
}
foreach ($p in $prefixes.binary_prefixes.PSObject.Properties) {
    $prefixRows += [PSCustomObject]@{ key = [string]$p.Name; factor = [double]$p.Value.f }
}
$prefixRows = $prefixRows | Sort-Object @{Expression={$_.key.Length};Descending=$true}, @{Expression={$_.key};Descending=$false}

$unitSymbolRows = @()
foreach ($p in $symbols.units.PSObject.Properties) {
    $unitSymbolRows += [PSCustomObject]@{ key = [string]$p.Name; value = [string]$p.Value }
}
$stateSymbolRows = @()
foreach ($p in $symbols.states.PSObject.Properties) {
    $stateSymbolRows += [PSCustomObject]@{ key = [string]$p.Name; value = [string]$p.Value }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("/* Auto-generated by scripts/generate_library_data.ps1 */")
$lines.Add("#ifndef OSFX_LIBRARY_DATA_GENERATED_H")
$lines.Add("#define OSFX_LIBRARY_DATA_GENERATED_H")
$lines.Add("")
$lines.Add("static const osfx_unit_record OSFX_UNIT_RECORDS[] = {")
foreach ($u in ($unitMap.Values | Sort-Object key)) {
    $lines.Add(('    {{"{0}", "{1}", "{2}", {3:R}, {4:R}, {5}}},' -f (Escape-CString $u.key), (Escape-CString $u.ucum), (Escape-CString $u.base_unit), $u.factor, $u.offset, $u.can))
}
$lines.Add("};")
$lines.Add("static const size_t OSFX_UNIT_COUNT = sizeof(OSFX_UNIT_RECORDS) / sizeof(OSFX_UNIT_RECORDS[0]);")
$lines.Add("")
$lines.Add("static const osfx_prefix_record OSFX_PREFIX_RECORDS[] = {")
foreach ($p in $prefixRows) {
    $lines.Add(('    {{"{0}", {1:R}}},' -f (Escape-CString $p.key), $p.factor))
}
$lines.Add("};")
$lines.Add("static const size_t OSFX_PREFIX_COUNT = sizeof(OSFX_PREFIX_RECORDS) / sizeof(OSFX_PREFIX_RECORDS[0]);")
$lines.Add("")
$lines.Add("static const osfx_symbol_pair OSFX_UNIT_SYMBOLS[] = {")
foreach ($s in ($unitSymbolRows | Sort-Object key)) {
    $lines.Add(('    {{"{0}", "{1}"}},' -f (Escape-CString $s.key), (Escape-CString $s.value)))
}
$lines.Add("};")
$lines.Add("static const size_t OSFX_UNIT_SYMBOL_COUNT = sizeof(OSFX_UNIT_SYMBOLS) / sizeof(OSFX_UNIT_SYMBOLS[0]);")
$lines.Add("")
$lines.Add("static const osfx_symbol_pair OSFX_STATE_SYMBOLS[] = {")
foreach ($s in ($stateSymbolRows | Sort-Object key)) {
    $lines.Add(('    {{"{0}", "{1}"}},' -f (Escape-CString $s.key), (Escape-CString $s.value)))
}
$lines.Add("};")
$lines.Add("static const size_t OSFX_STATE_SYMBOL_COUNT = sizeof(OSFX_STATE_SYMBOLS) / sizeof(OSFX_STATE_SYMBOLS[0]);")
$lines.Add("")
$lines.Add("#endif")

$lines | Set-Content -Encoding UTF8 $OutFile
Write-Host "[ok] generated $OutFile"

