#ifndef OSFX_BUILD_CONFIG_H
#define OSFX_BUILD_CONFIG_H

/* Auto-generated from Config.json */

#define OSFX_CFG_PLUGIN_TRANSPORT 1
#define OSFX_CFG_PLUGIN_TEST_PLUGIN 1
#define OSFX_CFG_PLUGIN_PORT_FORWARDER 1

#define OSFX_CFG_AUTOLOAD_TRANSPORT 1
#define OSFX_CFG_AUTOLOAD_TEST_PLUGIN 1
#define OSFX_CFG_AUTOLOAD_PORT_FORWARDER 1

#define OSFX_CFG_PAYLOAD_DEVICE_ID 1
#define OSFX_CFG_PAYLOAD_DEVICE_STATUS 1
#define OSFX_CFG_PAYLOAD_TIMESTAMP 1
#define OSFX_CFG_PAYLOAD_SUB_TEMPLATE_ID 1
#define OSFX_CFG_PAYLOAD_SENSOR_ID 1
#define OSFX_CFG_PAYLOAD_SENSOR_STATUS 1
#define OSFX_CFG_PAYLOAD_PHYSICAL_ATTRIBUTE 0
#define OSFX_CFG_PAYLOAD_NORMALIZED_VALUE 1
#define OSFX_CFG_PAYLOAD_GEOHASH_ID 0
#define OSFX_CFG_PAYLOAD_SUPPLEMENTARY_MESSAGE 1
#define OSFX_CFG_PAYLOAD_RESOURCE_URL 0

#endif
